version: "3.8"
services:
  auth-backend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
    ports:
      - 3000:3000
